services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn asto.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: asto.settings
