# Generated by Django 5.1.6 on 2025-04-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('gemstone', 'Gemstone'), ('rudraksh', 'Rudraksh'), ('yantras', 'Yantras')], max_length=20),
        ),
    ]
