# Generated by Django 5.1.6 on 2025-04-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_appointment_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_idd', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='cart/')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
