# Generated by Django 5.1.6 on 2025-04-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_idd',
            field=models.CharField(default='111', max_length=100),
        ),
    ]
